Added blog posts for Meetup0 and Meetup1.
osdc/blog pull request #4
Opened 2018-09-19 20:03 UTC by sidntrivedi012

2018-09-20 07:59 UTC, sidntrivedi012 commented
@vaibhavk @ryzokuken @saranshbarua Please review.

2018-09-20 12:27 UTC, ryzokuken requested changes
@sidntrivedi012 Great work! Just a couple of minor changes.

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/Open-source-M1/index.md
> +These are some of the simple yet daunting questions that many people have in mind. Some question up while the rest don't even care to understand it.And so, in order to remove this confusion or dilemm
These are some simple yet...

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/Open-source-M1/index.md
> +These are some of the simple yet daunting questions that many people have in mind. Some question up while the rest don't even care to understand it.And so, in order to remove this confusion or dilemm
Please add spaces after punctuation.

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/Open-source-M1/index.md
> +An integral part of organizing meetups is to make the community members interact and network with each other.So,the meetup started with an introduction part where each member has to introduce himself
Same thing about spaces after punctuation.

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/Open-source-M1/index.md
> +An integral part of organizing meetups is to make the community members interact and network with each other.So,the meetup started with an introduction part where each member has to introduce himself
Just use gender neutral language here.

> introduction part where participants had to introduce themselves and the technology they were working on/interested to work on.

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/Open-source-M1/index.md
> +A successful strategy of open-source contributions which should be followed in order to start contributing to the organizations was also discussed according to which one has to start with the basics
s/Docs/documentations

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/Open-source-M1/index.md
> +Further,a QnA round was held in which the community members were answered with the queries they had put forward regarding the the hurdles they faced while doing open-source contributions.
s/Further/Finally

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/Open-source-M1/index.md
> +Further,a QnA round was held in which the community members were answered with the queries they had put forward regarding the the hurdles they faced while doing open-source contributions.
> in which the community members asked questions regarding the the hurdles

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/Open-source-M1/index.md
> +The meetup finally ended with the announcement of the next meetup regarding "Introduction to Git/Github" since the month long celebration of Open Source i.e. [Hacktoberfest](https://hacktoberfest.dig
s/Open Source/open-source software

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/wanna-play-linux-meetup0/index.md
> +>One OS to rule them all,
A space between `>` and the sentence in this and all subsequent lines.

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/wanna-play-linux-meetup0/index.md
> +These magnificent lines by J.Scott Thayer themselves exhibit the power and superiority of Linux over other pieces of softwares or to be more precise,Kernels. Therefore, to provide the community membe
Spaces after punctuation.

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/wanna-play-linux-meetup0/index.md
> +These magnificent lines by J.Scott Thayer themselves exhibit the power and superiority of Linux over other pieces of softwares or to be more precise,Kernels. Therefore, to provide the community membe
s/Kernels/kernels

2018-09-20 12:27 UTC, ryzokuken commented on src/pages/wanna-play-linux-meetup0/index.md
> +This wargame simulation was followed by a QnA session in which the community members clarified their various doubts regarding using Linux and its Distros.The meetup finally ended with a lot of awesom
s/Distros/distros

2018-09-20 14:54 UTC, sidntrivedi012 commented
@ryzokuken Have made the changes. Please review.

2018-09-21 07:30 UTC, ryzokuken approved these changes
Looks great! Thanks.

2018-09-21 07:30 UTC, merged