Added favicon to the blog.
osdc/blog pull request #8
Opened 2018-09-21 10:17 UTC by sidntrivedi012

2018-09-21 10:18 UTC, sidntrivedi012 commented
@ryzokuken @saranshbarua Please review. 

Tried to use this plugin. https://github.com/Creatiwity/gatsby-plugin-favicon in order to add a favicon.

2018-09-21 18:23 UTC, ryzokuken commented
@sidntrivedi012 screenshot please?

2018-09-21 18:47 UTC, sidntrivedi012 commented
@ryzokuken Idk why Gatsby is not setting up on my system. It is giving an error https://paste.fedoraproject.org/paste/fZQa2UaFlNX3tXCofOAiwg. 

So,I couldn't run it. But, having seen the documentation of the favicon plugin, it seemed easy and so I made a PR.

2018-09-21 18:48 UTC, sidntrivedi012 commented
@ryzokuken Not able to debug the error. Please help.

2018-09-21 18:54 UTC, sidntrivedi012 commented
This one was debugged by installing Gatsby CLI. But, now one new error comes up - https://paste.fedoraproject.org/paste/z2B7XC0uDnC-UBbA~nbVcA .

2018-09-24 21:46 UTC, sidntrivedi012 commented
Closing it as tried it locally after debugging and it's not working.

2018-09-24 21:50 UTC, sidntrivedi012 commented
@ryzokuken @saranshbarua But, I think that it will make a good issue for the blog.

2018-10-26 16:36 UTC, ryzokuken commented
@sidntrivedi012 do you want to work on it?

2018-10-27 12:56 UTC, sidntrivedi012 commented
@ryzokuken Yes, will try to implement it.

2018-10-29 13:43 UTC, sidntrivedi012 commented
![screenshot from 2018-10-29 19-11-51](https://user-images.githubusercontent.com/31186013/47653419-8cedfe80-dbae-11e8-9317-6e9cfcb3c7bc.png)
@ryzokuken Please take a look. Just had to add the favicon.ico file in the static folder.

2018-10-29 14:05 UTC, ryzokuken approved these changes
Looks good to me. @saranshbarua wdyt.

2018-10-30 02:44 UTC, sidntrivedi012 commented
@ryzokuken @saranshbarua Made relevant changes required in #12 here. Please review.

2018-10-30 04:28 UTC, ryzokuken requested changes
This seems to be having the exact same whitespace issues. Please fix that.

Probably something wrong with your editor? Don't tell me you're using emacs.

2018-10-30 13:58 UTC, sidntrivedi012 commented
@ryzokuken Please check. 

Not using Emacs this time but Sublime Text ;)

2018-10-30 18:06 UTC, ryzokuken requested changes

2018-10-30 18:06 UTC, ryzokuken commented on src/components/Bio.js
> +          <strong>Open Source Developers Community</strong> who live in and around JIIT, Noida, India.
Thanks to sublime, the whitespace issues seem to be fixed now. Please reindent these properly and we'd be good to go.

2018-10-31 05:39 UTC, sidntrivedi012 commented
@ryzokuken Fixed the indentation. PTAL.

2018-10-31 09:22 UTC, ryzokuken approved these changes
LGTM.

2018-10-31 09:22 UTC, merged